# UAVScenes config for MonoScene transfer learning
# Launcher scripts override these paths by default.
uav_preprocess_root: "/root/Tuan/uavssc_project/data/processed/interval5/rgb_ssc_npz"
uav_data_root: "/root/Tuan/uavssc_project/data/raw/uavscenes_official"
uav_logdir: "/root/Tuan/uavssc_project/checkpoints/rgb_monoscene/manual_config_run"

scene_filter: ""
split_files:
  train: ""
  val: ""
  test: ""

load_pretrained: false
pretrained_model_path: ""
resume_from_checkpoint: ""
eval_checkpoint_path: "CHANGE ME"
eval_checkpoint_path: "/mnt/c/Study/Uni/B3/Intern/uavssc_project/checkpoints/rgb_monoscene/debug_b0_f64_lr1e5_clean2/uav_monoscene_uavscenes_1_sceneall_fs128_128_32_bs1_lr1e-05/checkpoints/epoch007val/mIoU0.05630.ckpt"

input_image_hw: [224, 320]
rgb_backbone: "tf_efficientnet_b0_ns"
rgb_pretrained: true
freeze_rgb_encoder: false

project_scale: 2
full_scene_size: [128, 128, 32]
feature: 64
n_relations: 4
frustum_size: 4

context_prior: false
relation_loss: false
fp_loss: false
CE_ssc_loss: true
sem_scal_loss: true
geo_scal_loss: true

project_1_2: false
project_1_4: false
project_1_8: false

max_epochs: 10
batch_size: 1
n_gpus: 1
num_workers_per_gpu: 8
precision: 16
lr: 1.0e-5
weight_decay: 1.0e-4
gradient_clip_val: 1.0
exp_prefix: "uav_monoscene"
run: 1

train_ratio: 0.70
val_ratio: 0.15
test_ratio: 0.15

eval_split: "val"
predict_output_root: "/root/Tuan/uavssc_project/results/qualitative/rgb_monoscene_predictions"
visualization_output_root: "/root/Tuan/uavssc_project/results/qualitative/rgb_monoscene_visualizations"
max_predict_samples: 50
max_visualization_files: 50
