fold: fold_D
train_scenes:
- HKisland
- AMtown
val_scenes:
- AMvalley
test_scenes:
- HKairport
train_samples_file: data/splits/scene_strict_cv/fold_D/train_samples.txt
val_samples_file: data/splits/scene_strict_cv/fold_D/val_samples.txt
test_samples_file: data/splits/scene_strict_cv/fold_D/test_samples.txt
